[package]
name = "markdown-rs"
version = "0.1.0"
authors = ["Daniel Toebe <dtoebe@gmail.com>"]
build = "build.rs"

[[bin]]
name = "rustdown"
path = "src/main.rs"

[dependencies]
qmlrs = "0.1.1"
markdown = "0.1"
